export const ON_TAG_PRESS = 'ON_TAG_PRESS';
export const SEARCH_TAG = 'SEARCH_TAG';
export const LOAD_QUESTIONS_DONE = 'LOAD_QUESTIONS_DONE';
export const SEARCH_TAG_START = 'SEARCH_TAG_START';
export const LOAD_MORE_QUESTIONS = 'LOAD_MORE_QUESTIONS';
